version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 605134465349.dkr.ecr.ca-central-1.amazonaws.com
      - REPO_NAME=finaltest
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_NAME .
      - echo Tagging the Docker image...
      - docker tag $REPO_NAME:latest 605134465349.dkr.ecr.ca-central-1.amazonaws.com/$REPO_NAME:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 605134465349.dkr.ecr.ca-central-1.amazonaws.com/$REPO_NAME:latest
artifacts:
  files:
    - '**/*'
  discard-paths: yes
